# fly.toml app configuration file generated for simple-youtube-downloader on 2024-02-24T10:18:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-youtube-downloader'
primary_region = 'nrt'

[build]
  dockerfile = 'cicd/Dockerfile'

[env]
  PORT = '8501'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
